### ISSUE TITLE
Particles not Shaded

### ISSUE THREAD

**Issue by JamsNJellies** [rre36/kappa_shader_web#4]
**Describe the bug**
Particles are not shaded and are always displayed at full brightness

**To Reproduce**
Break a block, place a torch, place an enderchest, anything that makes particles

**Expected behavior**
Particles are shaded.

**Screenshots**
![2020-04-18_15 45 13](https://user-images.githubusercontent.com/39382425/79640854-eb84af00-818b-11ea-8bbe-4bc8511b44d1.png)
![2020-04-18_15 45 19](https://user-images.githubusercontent.com/39382425/79640856-f0496300-818b-11ea-9ba8-ba63a3b2620d.png)

**Desktop:**
Operating System: Windows 10 Pro 1909 build 18363.720
Graphics Card: EVGA GTX 1050 2GB Superclocked
Graphics Driver Version: 445.75
Game Version: 1.15.2
OF Version: 1.15.2_pre13
CPU: Intel i5-4570 @ 3.20GHz
RAM: 8GB
Any Overlay Software running: None

**Additional context**

**Comment by rre36** [comment]
Optifine for Minecraft 1.15.2 is not yet finished and has many known issues which manifest as broken enchantment overlays, bright areas below the horizon, broken Motionblur on the player's hand and many more. Please wait for the full release of Optifine for 1.15.2 before reporting bugs on that Minecraft version.
